apiVersion: v1
kind: Service
metadata:
  name: sw2p2-dlreportes-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "sw2p2-dlreportes-lb"
spec:
  type: LoadBalancer
  selector:
    app: sw2p2-dlreportes
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
